# Generated by Django 4.2.30 on 2026-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=50, verbose_name='Identifiant unique du capteur')),
                ('alert_type', models.CharField(choices=[('fire', 'Incendie'), ('technical', 'Technique')], max_length=20, verbose_name="Type d'alerte")),
                ('site', models.CharField(max_length=100)),
                ('batiment', models.CharField(max_length=100)),
                ('salle', models.CharField(max_length=100)),
                ('machine', models.CharField(blank=True, max_length=100, null=True)),
                ('motifs', models.JSONField(default=list, verbose_name="Motifs de l'alerte")),
                ('actions', models.JSONField(default=list, verbose_name='Actions menées')),
                ('impact', models.CharField(choices=[('Aucun', 'Aucun'), ('Mineur', 'Mineur'), ('Majeur', 'Majeur')], default='Aucun', max_length=20)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Précisions / Commentaires')),
                ('duration', models.IntegerField(default=0, verbose_name="Durée de l'alerte (secondes)")),
                ('timestamp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Heure signalée par le dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement backend")),
            ],
        ),
    ]
