# Generated by Django 4.2.30 on 2026-07-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(verbose_name='Contenu du bilan mensuel (Markdown)')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('month', models.IntegerField(verbose_name='Mois (1-12)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic Kafka')),
                ('payload', models.JSONField(verbose_name='Payload JSON brut')),
                ('processed', models.BooleanField(db_index=True, default=False, verbose_name='Traité pour résumé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_text', models.TextField(verbose_name='Contenu du briefing hebdomadaire (Markdown)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('monthly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_briefings', to='resume.monthlyreport', verbose_name='Bilan mensuel associé')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(verbose_name='Contenu du résumé (Markdown)')),
                ('events_count', models.IntegerField(verbose_name="Nombre d'événements inclus")),
                ('start_time', models.DateTimeField(verbose_name='Début de la période')),
                ('end_time', models.DateTimeField(verbose_name='Fin de la période')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('weekly_briefing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodic_summaries', to='resume.weeklybriefing', verbose_name='Briefing hebdomadaire associé')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
